apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pods
  template:
    metadata:
      labels:
        app: pods
    spec:
      containers:
      - image: okteto.dev/go-hello-world:1.0.0
        name: pods

---

apiVersion: v1
kind: Service
metadata:
  name: pods
spec:
  type: ClusterIP
  ports:
  - name: "pods"
    port: 8080
  selector:
    app: pods

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pods
  namespace: mig-elgt
  annotations:
    dev.okteto.com/generate-host: pods
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: pods
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb
    spec:
      securityContext:
        fsGroup: 1001      
      initContainers:
      containers:
      - name: mongodb
        image: docker.io/bitnami/mongodb:4.0.12-debian-9-r43
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        env:
        - name: MONGODB_PASSWORD
          value: "foobar"
        - name: MONGODB_ROOT_PASSWORD
          value: "foobar"
        - name: MONGODB_USERNAME
          value: "okteto"
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_DATABASE
          value: "okteto"
        - name: MONGODB_ENABLE_IPV6
          value: "no"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
        ports:
        - name: mongodb
          containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /bitnami/mongodb
          subPath: 
        resources:
          {}
      volumes:
      - name: data
        emptyDir: {}
